#!/bin/sh
# --- SDE-COPYRIGHT-NOTE-BEGIN ---
# This copyright note is auto-generated by ./scripts/Create-CopyPatch.
#
# Filename: target/esa/initramfs/sbin_init.d_trymount.sh
# Copyright (C) 2012 The OpenSDE Project
#
# More information can be found in the files COPYING and README.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License. A copy of the
# GNU General Public License can be found in the file COPYING.
# --- SDE-COPYRIGHT-NOTE-END ---

root_dev=
root_type=
root_mode=
squashfs=

die() {
	echo "trymount: $*" >&2
	exit 1
}

for x in $(cat /proc/cmdline); do
	v="${x#*=}"
	case "$x" in
	root=*) root_dev="$v" ;;
	rw|ro)  root_mode="$x" ;;
	squashfs=*) squashfs="$v" ;;
	esac
done

[ -n "$root_dev" ] || die "no root given"

TYPE=
eval $(blkid "$root_dev" 2> /dev/null | grep "^$root_dev: " | cut -d' ' -f2-)

[ -n "$TYPE" ] || die "$root_dev: bad root"
root_type="$TYPE"

A=/aufs
R=/rootfs
RA=$R/var/run/.aufs

mount2() {
	local mp="$1" t="$2"
	shift 2
	[ -d "$mp" ] || mkdir -p "$mp"
	mount -t "$t" "$@" "$mp"
}

mmount() {
	[ -d "$2" ] || mkdir -p "$2"
	mount --move "$1" "$2"
}

if [ -z "$squashfs" ]; then
	D="$R"
else
	D="$A.real"
fi

set -e

mount2 "$D" "$root_type" ${root_mode:+-o $root_mode} "$root_dev"
[ "$D" != "$R" ] || exit 0

mount2 "$A.ro" squashfs -o loop "$A.real$squashfs"
mount2 "$A.rw" tmpfs "rootfs.rw"
mount2 "$R" aufs -o "dirs=$A.rw=rw:$A.ro=ro" "rootfs.union"

mmount "$A.real" "$R/mnt"
mmount "$A.ro" "$RA.ro"
mmount "$A.rw" "$RA.rw"
